name: Run Selenium Tests (Ayden)

on:
  push:
    branches:
      - "ayden"
      - "main"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/test_ayden.yaml"

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium

      - name: Install Chrome browser
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          sudo apt install -y chromium-chromedriver

      - name: Start Flask app in background
        run: |
          nohup python youface.py &
          sleep 5

      - name: Run Selenium tests
        run: |
          python tests/test_profile.py
