name: Run Selenium Tests (Andy)

on:
  push:
    branches:
      - "andy"
      - "main"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/test_andy.yaml"

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install matching ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip jq curl
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)
      
          echo "Detected full Chrome version: $CHROME_VERSION"
          echo "Detected Chrome major version: $CHROME_MAJOR_VERSION"
      
          LATEST_MATCHING=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" \
            | jq -r ".channels.Stable.downloads.chromedriver[] | select(.platform == \"linux64\") | .url")
      
          echo "Downloading matching ChromeDriver from: $LATEST_MATCHING"
      
          wget "$LATEST_MATCHING" -O chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Start Flask app in background
        run: |
          nohup python youface.py &
          sleep 5

      - name: Run Selenium tests
        run: |
          python tests/test_andy.py