name: Run Selenium Tests (Ayden)

on:
  push:
    branches:
      - "ayden"
      - "main"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/test_ayden.yaml"

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          LATEST=$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/${LATEST}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Start Flask app in background
        run: |
          nohup python youface.py &
          sleep 5

      - name: Run Selenium tests
        run: |
          python tests/test_profile.py
